name = "HydroPowerSimulations"
uuid = "fc1677e0-6ad7-4515-bf3a-bd6bf20a0b1b"
version = "0.9.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
InfrastructureSystems = "2cd47ed4-ca9b-11e9-27f2-ab636a7671f1"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
PowerSimulations = "e690365d-45e2-57bb-ac84-44ba829e73c4"
PowerSystems = "bcd98974-b02a-5e2f-9ee0-a103f5c450dd"

[compat]
Dates = "1"
InfrastructureSystems = "2"
PowerSimulations = "^0.28"
PowerSystems = "4"
julia = "^1.6"
JuMP = "1"
